// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/invoicer/invoicer.proto

package invoicer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Amount struct {
	Amount               int64    `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency             string   `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Amount) Reset()         { *m = Amount{} }
func (m *Amount) String() string { return proto.CompactTextString(m) }
func (*Amount) ProtoMessage()    {}
func (*Amount) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fba824f9acb56eb, []int{0}
}

func (m *Amount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Amount.Unmarshal(m, b)
}
func (m *Amount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Amount.Marshal(b, m, deterministic)
}
func (m *Amount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Amount.Merge(m, src)
}
func (m *Amount) XXX_Size() int {
	return xxx_messageInfo_Amount.Size(m)
}
func (m *Amount) XXX_DiscardUnknown() {
	xxx_messageInfo_Amount.DiscardUnknown(m)
}

var xxx_messageInfo_Amount proto.InternalMessageInfo

func (m *Amount) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Amount) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

type CreateRequest struct {
	Amount               *Amount  `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	From                 string   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fba824f9acb56eb, []int{1}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetAmount() *Amount {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *CreateRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *CreateRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

type CreateResponse struct {
	Pdf                  []byte   `protobuf:"bytes,1,opt,name=pdf,proto3" json:"pdf,omitempty"`
	Docx                 []byte   `protobuf:"bytes,2,opt,name=docx,proto3" json:"docx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fba824f9acb56eb, []int{2}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetPdf() []byte {
	if m != nil {
		return m.Pdf
	}
	return nil
}

func (m *CreateResponse) GetDocx() []byte {
	if m != nil {
		return m.Docx
	}
	return nil
}

func init() {
	proto.RegisterType((*Amount)(nil), "Amount")
	proto.RegisterType((*CreateRequest)(nil), "CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "CreateResponse")
}

func init() {
	proto.RegisterFile("internal/invoicer/invoicer.proto", fileDescriptor_6fba824f9acb56eb)
}

var fileDescriptor_6fba824f9acb56eb = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0xd0, 0x31, 0x4f, 0x83, 0x40,
	0x14, 0xc0, 0xf1, 0x00, 0x06, 0xeb, 0xb3, 0xa2, 0xb9, 0xc1, 0x90, 0x2e, 0x12, 0x26, 0x34, 0x29,
	0x24, 0x35, 0x3a, 0xb9, 0xa8, 0x93, 0xeb, 0xc5, 0xc9, 0x8d, 0x1e, 0x57, 0x7a, 0x89, 0xdc, 0xc3,
	0xc7, 0x3b, 0xa3, 0xdf, 0xde, 0xf4, 0x8a, 0x24, 0x6c, 0xff, 0x77, 0xc3, 0x2f, 0xf7, 0x1e, 0x64,
	0xc6, 0xb2, 0x26, 0x5b, 0x7f, 0x56, 0xc6, 0x7e, 0xa3, 0x51, 0x9a, 0xa6, 0x28, 0x7b, 0x42, 0xc6,
	0xfc, 0x09, 0xe2, 0xe7, 0x0e, 0x9d, 0x65, 0x71, 0x0d, 0x71, 0xed, 0x2b, 0x0d, 0xb2, 0xa0, 0x88,
	0xe4, 0x38, 0x89, 0x15, 0x2c, 0x94, 0x23, 0xd2, 0x56, 0xfd, 0xa6, 0x61, 0x16, 0x14, 0x67, 0x72,
	0x9a, 0xf3, 0x77, 0xb8, 0x78, 0x25, 0x5d, 0xb3, 0x96, 0xfa, 0xcb, 0xe9, 0x81, 0xc5, 0xcd, 0x0c,
	0x39, 0xdf, 0x9c, 0x96, 0x47, 0x7d, 0xd2, 0x04, 0x9c, 0xec, 0x08, 0xbb, 0x51, 0xf2, 0x2d, 0x12,
	0x08, 0x19, 0xd3, 0xc8, 0xbf, 0x84, 0x8c, 0xf9, 0x23, 0x24, 0xff, 0xea, 0xd0, 0xa3, 0x1d, 0xb4,
	0xb8, 0x82, 0xa8, 0x6f, 0x76, 0xde, 0x5c, 0xca, 0x43, 0x1e, 0x9c, 0x06, 0xd5, 0x8f, 0x77, 0x96,
	0xd2, 0xf7, 0xe6, 0x01, 0x16, 0x6f, 0xe3, 0x76, 0xe2, 0x16, 0xe2, 0xa3, 0x21, 0x92, 0x72, 0xf6,
	0xc5, 0xd5, 0x65, 0x39, 0xc7, 0x5f, 0xee, 0x3e, 0x8a, 0xd6, 0xf0, 0xde, 0x6d, 0x4b, 0x85, 0x5d,
	0x55, 0x5b, 0x36, 0xeb, 0xc6, 0xed, 0xc9, 0xd8, 0xb6, 0x6a, 0x71, 0xdd, 0x52, 0xaf, 0xa6, 0xa3,
	0x6d, 0x63, 0x7f, 0xb5, 0xfb, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4a, 0x35, 0xf0, 0xe1, 0x59,
	0x01, 0x00, 0x00,
}
